### ISSUE TITLE
Reimplement Theme Check Ruby LSP features in @shopify/liquid-language-server

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#24]
```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/liquid-language-server/issues/27
- [ ] https://github.com/Shopify/liquid-language-server/issues/26
- [ ] https://github.com/Shopify/theme-tools/issues/25
- [ ] https://github.com/Shopify/theme-tools/issues/26
```
