### ISSUE TITLE
Highlight and rename html nodes in pairs

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#241]
**Describe the solution you'd like**
- If you put your mouse over an opening or close HTML tag, the other one should be highlighted (e.g. div /div, a /a, etc.)
- If you F2 on the tag name, then the closing part should get renamed as well

```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/theme-tools/issues/491
- [ ] https://github.com/Shopify/theme-tools/issues/490
- [ ] https://github.com/Shopify/theme-tools/issues/489
- [ ] https://github.com/Shopify/theme-tools/issues/492
- [ ] https://github.com/Shopify/theme-tools/issues/493
- [ ] https://github.com/Shopify/theme-tools/issues/494
```

**Additional context**
We can do this with the following LSP features:
- https://code.visualstudio.com/api/language-extensions/programmatic-language-features#rename-symbols
- https://code.visualstudio.com/api/language-extensions/programmatic-language-features#highlight-all-occurrences-of-a-symbol-in-a-document
- https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_linkedEditingRange

**Comment by charlespwd** [comment]
Closing this one since we don't plan on doing the other two just yet.
