### ISSUE TITLE
Reimplement Intelligent Code Completion

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#25]
```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/liquid-language-server/issues/50
- [ ] https://github.com/Shopify/liquid-language-server/issues/52
- [ ] https://github.com/Shopify/liquid-language-server/issues/61
- [ ] https://github.com/Shopify/liquid-language-server/issues/56
- [ ] https://github.com/Shopify/liquid-language-server/issues/62
- [ ] https://github.com/Shopify/liquid-language-server/issues/58
- [ ] https://github.com/Shopify/theme-tools/issues/30
- [ ] https://github.com/Shopify/theme-tools/issues/29
- [ ] https://github.com/Shopify/liquid-language-server/issues/55
- [ ] https://github.com/Shopify/theme-tools/issues/31
- [ ] https://github.com/Shopify/liquid-language-server/issues/60
- [ ] https://github.com/Shopify/code-mirror-language-client/issues/10
- [ ] https://github.com/Shopify/theme-tools/issues/28
- [ ] https://github.com/Shopify/theme-tools/issues/27
- [ ] https://github.com/Shopify/theme-tools/issues/32
```
