### ISSUE TITLE
Theme block support

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#545]
**Is your feature request related to a problem? Please describe.**
Theme blocks

**Describe the solution you'd like**
```[tasklist]
### Tasks
- [ ] https://github.com/Shopify/theme-tools/issues/570
- [ ] https://github.com/Shopify/theme-tools/issues/623
- [ ] https://github.com/Shopify/theme-tools/issues/624
- [ ] https://github.com/Shopify/theme-tools/issues/602
- [ ] https://github.com/Shopify/theme-tools/issues/625
- [ ] https://github.com/Shopify/theme-tools/issues/571
- [ ] https://github.com/Shopify/theme-tools/issues/569
- [ ] https://github.com/Shopify/theme-tools/issues/626
- [ ] https://github.com/Shopify/theme-tools/issues/627
- [ ] https://github.com/Shopify/theme-tools/issues/628
```

**Comment by aswamy** [comment]
### Known issues we will be tackling on separately after this mega-ticket

https://github.com/Shopify/theme-tools/issues/751
https://github.com/Shopify/theme-tools/issues/755
https://github.com/Shopify/theme-tools/issues/750
https://github.com/Shopify/theme-tools/issues/754
https://github.com/Shopify/theme-tools/issues/776

### Nice to have features

https://github.com/Shopify/theme-tools/issues/757
https://github.com/Shopify/theme-tools/issues/749
