### ISSUE TITLE
Metafield theme-check

### ISSUE THREAD

**Issue by aswamy** [Shopify/theme-tools#575]
**Is your feature request related to a problem? Please describe.**

Follows up https://github.com/Shopify/theme-tools/issues/502
We need to verify if metafields being used in the code are valid. If the metafield does not exist, you should see a warning when running `shopify theme check`

**Describe the solution you'd like**

For themes:
- running `shopify theme check` should verify if the metafield exists on your shop
- If you don't have the metafield, you should get a warning message

For theme app extensions:
- TAEs might have their own metafield definitions that are specific to it (see https://shopify.dev/docs/apps/build/custom-data/metafields/use-app-data-metafields)
- running `shopify theme check` should verify if the metafield exists on your shop OR if the metafield is defined for the app itself
- If you don't have the metafield, you should get a warning message

**Tasks**
- [ ] Update theme-check in theme-tools to error out when metafield definitions dont exist
- [ ] Add lint ignore rules in Dawn + Horizon where we use metafields that don't exist in any shops by default
- [ ] Update CLI so there is a warning when running `theme check` and metafield isnt defined

NOTE: There are a few differences when you pull metafield definitions from CLI or from Theme Access App via CLI
