### ISSUE TITLE
Follow up on 599

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#600]
#599 follow-ups

Mostly deal with theme app extensions with the same level of niceness. I've kind of ignored them in order to ship 599 really quickly before burst. 

```[tasklist]
### Tasks
- [ ] Translate Theme App Extension schemas into TS interfaces
- [ ] Inject `getAppBlockSchema('')` from language server/runChecks
- [ ] Inject `getAppBlockSchema('')` in theme-check-node
- [ ] https://github.com/Shopify/theme-tools/issues/601
```
