### ISSUE TITLE
Theme block JSON preset validation

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#624]
Maybe duplicate of what @navdeep5 is doing? 

Should we add a tasklist in here?

Or a duplicate of https://github.com/Shopify/theme-tools/issues/602

Top of mind:
```[tasklist]
### Tasks
- [x] Make sure setting id/value pairs in presets match the block
- [x] Make sure block type is accepted by parent
- [x] Preset names can be a translation key. Show an error when this translation key does not resolve to a value. (can share overlap to the work done for verifying schema name value). This validation should work for section presets as well.
- [x] ... ?
```

**Comment by bakura10** [comment]
I think this is somehow related. But since theme blocks are introduced (I think) we can now connect a block value as a default. For instance, inside a section, I have this block:

```
"blocks": [
    {
      "type": "collection",
      "name": "t:sections.featured_collections.blocks.collection.name",
      "settings": [
        {
          "type": "collection",
          "id": "collection",
          "label": "t:sections.featured_collections.blocks.collection.collection"
        },
        {
          "type": "text",
          "id": "title",
          "label": "t:global.text.title",
          "default": "{{ block.settings.collection.title }}"
        }
  }
]
```

This is convenient and allow to automatically connect the title with the collection's title of the block.

Theme check report does not currently allow that though:

<img width="589" alt="Image" src="https://github.com/user-attachments/assets/0476b47d-9dbc-415e-a480-7201e0984d5e" />

I am not sure if this is expected @charlespwd

**Comment by charlespwd** [comment]
Hmm that's def a bug. Looks like Liquid in `{% schema %}` is being visited but shouldn't be.
