### ISSUE TITLE
Theme block JSON preset setting + default setting completion/hover

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#625]
Requirements:
- Key completion of `presets.[].settings` (same file)

```liquid
{% schema %}
{
  "name": "Header Announcement",
  "blocks": [{ "type": "slide" }],
  "settings": [
    {
      "type": "text",
      "id": "my-text",
      "label": "Text"
    },
    {
      "type": "text",
      "id": "my-number",
      "label": "Text"
    }
  ],
  "presets": [
    {
      "name": "Header Announcement",
      "settings": {
        "█": "<-- should complete 'my-number', 'my-text'"
      },
    }
  ],
  "default": {
    "settings": {
      "█t": "<-- should complete 'my-number', 'my-text'"
    }
  }
}
{% endschema %}
```

```[tasklist]
### Tasks
- [x] Preset setting completion
- [x] Preset setting hover
- [x] Default setting completion
- [x] Default setting hover
```
